{
 "title": "Avistagem e detecção",
 "description": "Dashbord do número de avistamentos",
 "time": { "from": "2017-12-03T02:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "especie",
    "label": "Especies",
    "query": "SELECT DISTINCT especie FROM tb_avistagem_deteccao"
   },
   {
    "name": "mes",
    "label": "Mês",
    "query": "SELECT DISTINCT mes_avistagem FROM tb_avistagem_deteccao"
   },
   {
    "name": "expedicao",
    "label": "Expedição",
    "query": "SELECT DISTINCT expedicao FROM tb_avistagem_deteccao"
   },
   {
    "name": "registro",
    "label": "Registro da avistagem",
    "query": "SELECT DISTINCT registro FROM tb_avistagem_deteccao"
   }
  ]
 },
 "panels": [
  {
   "title": "Ponstos de avistagens",
   "type": "geomap",
   "gridPos": { "h": 19, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "sentinelas",
     "rawSql": "SELECT latitude as \"Latitude\",\r\n  longitude as \"Longitude\",\r\n  expedicao as \"Expedição\",\r\n  navio as \"Navio da expedição\", \r\n  data AS \"Time\"\r\nFROM sentinelas.tb_avistagem_deteccao \r\nWHERE ('${especie:raw}' = 'All' OR especie LIKE '${especie:raw}') AND\r\n      ('${mes:raw}' = 'All' OR mes_avistagem LIKE '${mes:raw}') AND\r\n      ('${expedicao:raw}' = 'All' OR expedicao LIKE '${expedicao:raw}') AND\r\n      ('${registro:raw}' = 'All' OR registro LIKE '${registro:raw}')"
    }
   ]
  },
  {
   "title": "Avistamento grupos",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 11, "x": 13, "y": 0 },
   "targets": [
    {
     "dataset": "sentinelas",
     "rawSql": "SELECT data, tamanho_grupo_minimo AS \"Tamanho mínimo do grupo\", tamanho_grupo_maximo AS \"Tamanho máximo do grupo\"\r\nFROM sentinelas.tb_avistagem_deteccao \r\nWHERE ('${especie:raw}' = 'All' OR especie LIKE '${especie:raw}') AND\r\n      ('${mes:raw}' = 'All' OR mes_avistagem LIKE '${mes:raw}') AND\r\n      ('${expedicao:raw}' = 'All' OR expedicao LIKE '${expedicao:raw}') AND\r\n      ('${registro:raw}' = 'All' OR registro LIKE '${registro:raw}')\r\nLIMIT 6"
    },
    { "dataset": "mysql" }
   ]
  },
  {
   "title": "Ocorrências dos avistamentos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 11 },
   "targets": [
    {
     "dataset": "sentinelas",
     "rawSql": "SELECT\r\n  $__timeGroupAlias(data, 1d),\r\n  COUNT(*) AS Avistagens\r\nFROM\r\n  tb_avistagem_deteccao\r\nWHERE\r\n  $__timeFilter(data) AND\r\n  ('${especie:raw}' = 'All' OR especie LIKE '${especie:raw}') AND\r\n  ('${mes:raw}' = 'All' OR mes_avistagem LIKE '${mes:raw}') AND\r\n  ('${expedicao:raw}' = 'All' OR expedicao LIKE '${expedicao:raw}') AND\r\n  ('${registro:raw}' = 'All' OR registro LIKE '${registro:raw}')\r\nGROUP BY\r\n  1\r\n"
    }
   ]
  }
 ]
}